[package]
name = "no-construct-attr"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6"

[dependencies.syn]
version = "0.15"
features = ["full"]

[lib]
proc-macro = true
